---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
spec:
  containers:
    - name: web-server
      image: quay.io/ocsci/nginx:fio
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
  volumes:
    - ephemeral:
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
            labels:
              test: ephemeral
              type: my-frontend-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: ocs-storagecluster-ceph-rbd
            volumeMode: Filesystem
      name: scratch-volume
